insert into users values ('carlos guzman', '12345', 'CAG')
insert into users values ('rafael anaya','12345','RAF')
insert into users values ('amanda gomez','12345','AMA')
insert into users values ('carlos rubalcava','12345','CAR')
insert into users values ('griselda blanco','12345','GRB')